### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by 4lexbit** [biometrickz/notifier_bot#1]
https://github.com/biometrickz/notifier_bot/blob/c8d086fb44ba7ce08015cdf522312ab535c0826e/docker-compose.yml#L20

**Comment by 4lexbit** [comment]
https://github.com/biometrickz/notifier_bot/blob/c8d086fb44ba7ce08015cdf522312ab535c0826e/Dockerfile#L15

in your case it is better to use the name main

**Comment by 4lexbit** [comment]
https://github.com/biometrickz/notifier_bot/blob/c8d086fb44ba7ce08015cdf522312ab535c0826e/main/bot.py#L37

save this data to disk, u may take snapshots by user key or write file (check OAF)

**Comment by rashtv** [comment]
> https://github.com/biometrickz/notifier_bot/blob/c8d086fb44ba7ce08015cdf522312ab535c0826e/docker-compose.yml#L20

-> https://github.com/biometrickz/notifier_bot/blob/9f3d8ec93ea9cc7db574c4437d243bde13d53590/docker-compose.yml#L20
____________________________

> https://github.com/biometrickz/notifier_bot/blob/c8d086fb44ba7ce08015cdf522312ab535c0826e/Dockerfile#L15
> 
> in your case it is better to use the name main

-> https://github.com/biometrickz/notifier_bot/blob/9f3d8ec93ea9cc7db574c4437d243bde13d53590/Dockerfile#L15
____________________________

> https://github.com/biometrickz/notifier_bot/blob/c8d086fb44ba7ce08015cdf522312ab535c0826e/main/bot.py#L37
> 
> save this data to disk, u may take snapshots by key or write file (check OAF)

-> fixed using RDB persistence / snapshots
https://github.com/biometrickz/notifier_bot/blob/9f3d8ec93ea9cc7db574c4437d243bde13d53590/main/bot.py#L38
